"""Public API of the plot-planning core."""

from .domain import (
    Building,
    ARC_VARIANTS,
    ContextArea,
    ContextLinearObject,
    DomainValidationError,
    FENCE_OBJECT_ID,
    NATURE_VARIANTS,
    FenceStyle,
    HatchStyle,
    LayoutVariant,
    Plot,
    PlotDimensions,
    PlotMarker,
    Point2D,
    PrimitiveObject,
    Project,
    Rgba,
    RoofSpec,
    SiteFeature,
    Size2D,
    Size3D,
    Surroundings,
    WellStructure,
)
from .editor import ProjectEditor
from .geometry import (
    building_inside_plot,
    feature_inside_plot,
    footprint_corners,
    point_in_polygon,
    primitive_inside_plot,
    project_geometry_issues,
)
from .json_repository import JsonProjectRepository
from .ports import ProjectRepository

__all__ = [
    "Building",
    "ARC_VARIANTS",
    "ContextArea",
    "ContextLinearObject",
    "DomainValidationError",
    "FENCE_OBJECT_ID",
    "NATURE_VARIANTS",
    "FenceStyle",
    "HatchStyle",
    "JsonProjectRepository",
    "LayoutVariant",
    "Plot",
    "PlotDimensions",
    "PlotMarker",
    "Point2D",
    "PrimitiveObject",
    "Project",
    "ProjectEditor",
    "ProjectRepository",
    "Rgba",
    "RoofSpec",
    "SiteFeature",
    "Size2D",
    "Size3D",
    "Surroundings",
    "WellStructure",
    "building_inside_plot",
    "feature_inside_plot",
    "footprint_corners",
    "point_in_polygon",
    "primitive_inside_plot",
    "project_geometry_issues",
]
